---

- name: Install required packages
  hosts: all
  tasks:
    - name: Install required packages
      become: yes
      apt:
        name: ['tmux', 'git', 'ca-certificates', 'python3-pip']
        state: present

- name: Install docker
  tags: docker_install
  hosts: all
  roles:
    - docker_role

- name: Install asterisk service
  tags: service_config
  hosts: all
  vars:
    remote_build: true
    git_repository: https://github.com/Pgm-LabRedesYServicios/practica2_1
    git_repository_destination: /tmp/asterisk
    git_repository_tag: master
    service_name: asterisk_docker
    docker_image_tag: latest
    docker_command: >
      /usr/bin/docker run --rm -i
      --name "{{ service_name }}"
      -v "${PWD}/../logs":/var/log/asterisk
      -v "${PWD}/configs":/etc/asterisk
      -p 5060:5060
      -p 8088:8088
      -p 5038:5038
      "{{ service_name }}"
  roles:
    - {role: simple-deploy-docker-role}
